name: Django CI 
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Pull latest version
      uses: actions/checkout@v3        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt install wget -y
        wget https://dlm.mariadb.com/2678574/Connectors/c/connector-c-3.3.3/mariadb-connector-c-3.3.3-debian-bullseye-amd64.tar.gz -O- | tar -zxf - --strip-components=1 -C /us
        sudo apt install libmariadb3 libmariadb-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Run MariaDB
      run: |
        docker-compose up -d        
    - name: run
      run: python manage.py runserver 8001
   
