# Generated by Django 5.0.6 on 2024-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("db_host", models.CharField(max_length=255)),
                ("db_port", models.IntegerField()),
                ("db_root", models.CharField(max_length=255)),
                ("root_pw", models.CharField(max_length=255)),
                ("secret_key", models.TextField()),
                ("salt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
