# Generated by Django 5.0.6 on 2024-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="db",
            name="url_id",
            field=models.CharField(max_length=64),
        ),
    ]
